name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: natemacfadden/community@master
      - name: Run GitHub File Sync
        uses: natemacfadden/core@master
        with:
          GH_PAT: ${{ secrets.REPO_SYNC_TOKEN }}