name: Repository Sync

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "natemacfadden/community"
        source_token: ${{ secrets.GITHUB_TOKEN }}
        dest_repo: "natemacfadden/core"
        dest_token: ${{ secrets.REPO_SYNC_TOKEN }}
