name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: natemacfadden/community@main
      - name: Run GitHub File Sync
        uses: natemacfadden/core@main
        with:
          GH_PAT: ${{ secrets.REPO_SYNC_TOKEN }}